# Created with YamlCreate.ps1 v2.4.3 $debug=AUSU.CRLF.7-4-6.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: JRSoftware.InnoSetup
PackageVersion: 6.5.1
MinimumOSVersion: 6.1.0.0
InstallerType: inno
FileExtensions:
- iss
AppsAndFeaturesEntries:
- DisplayName: Inno Setup version 6.5.1
  ProductCode: Inno Setup 6_is1
RepairBehavior: installer
Installers:
- Architecture: x86
  Scope: machine
  InstallerUrl: https://jrsoftware.org/download.php/innosetup-6.5.1.exe
  InstallerSha256: fb13f30baf6d0a5f0c96759598ba68553567c5a6e4edbc61b7508f184c72f8a3
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: x86
  Scope: user
  InstallerUrl: https://jrsoftware.org/download.php/innosetup-6.5.1.exe
  InstallerSha256: fb13f30baf6d0a5f0c96759598ba68553567c5a6e4edbc61b7508f184c72f8a3
  InstallerSwitches:
    Custom: /CURRENTUSER
ManifestType: installer
ManifestVersion: 1.10.0
